/*
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DemoStandaloneSetup extends DemoStandaloneSetupGenerated {

	public static void doSetup() {
		new DemoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
