/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.demo.mydsl.demo.DemoFactory
 * @model kind="package"
 * @generated
 */
public interface DemoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "demo";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/demo/mydsl/Demo";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "demo";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DemoPackage eINSTANCE = org.xtext.demo.mydsl.demo.impl.DemoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ModelImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ImageImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 1;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__INSTRUCTION = 0;

  /**
   * The feature id for the '<em><b>Suite inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__SUITE_INST = 1;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl <em>Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.SuiteImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getSuite()
   * @generated
   */
  int SUITE = 2;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE__INSTRUCTION = 0;

  /**
   * The feature id for the '<em><b>Suite inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE__SUITE_INST = 1;

  /**
   * The number of structural features of the '<em>Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.InstImpl <em>Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.InstImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getInst()
   * @generated
   */
  int INST = 3;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST__NOMBRE = 0;

  /**
   * The number of structural features of the '<em>Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.GoImpl <em>Go</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.GoImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getGo()
   * @generated
   */
  int GO = 4;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__NOMBRE = INST__NOMBRE;

  /**
   * The number of structural features of the '<em>Go</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_FEATURE_COUNT = INST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TurnImpl <em>Turn</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TurnImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTurn()
   * @generated
   */
  int TURN = 5;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN__NOMBRE = INST__NOMBRE;

  /**
   * The number of structural features of the '<em>Turn</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_FEATURE_COUNT = INST_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TlImpl <em>Tl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TlImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTl()
   * @generated
   */
  int TL = 6;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TL__NOMBRE = TURN__NOMBRE;

  /**
   * The number of structural features of the '<em>Tl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TL_FEATURE_COUNT = TURN_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TrImpl <em>Tr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TrImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTr()
   * @generated
   */
  int TR = 7;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TR__NOMBRE = TURN__NOMBRE;

  /**
   * The number of structural features of the '<em>Tr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TR_FEATURE_COUNT = TURN_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.demo.mydsl.demo.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.demo.mydsl.demo.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.demo.mydsl.demo.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see org.xtext.demo.mydsl.demo.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Image#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.xtext.demo.mydsl.demo.Image#getInstruction()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Instruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Image#getSuite_inst <em>Suite inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Suite inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Image#getSuite_inst()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Suite_inst();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Suite <em>Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Suite</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite
   * @generated
   */
  EClass getSuite();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Suite#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite#getInstruction()
   * @see #getSuite()
   * @generated
   */
  EReference getSuite_Instruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Suite#getSuite_inst <em>Suite inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Suite inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite#getSuite_inst()
   * @see #getSuite()
   * @generated
   */
  EReference getSuite_Suite_inst();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Inst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Inst
   * @generated
   */
  EClass getInst();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.demo.mydsl.demo.Inst#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.demo.mydsl.demo.Inst#getNombre()
   * @see #getInst()
   * @generated
   */
  EAttribute getInst_Nombre();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Go <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go</em>'.
   * @see org.xtext.demo.mydsl.demo.Go
   * @generated
   */
  EClass getGo();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Turn <em>Turn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn</em>'.
   * @see org.xtext.demo.mydsl.demo.Turn
   * @generated
   */
  EClass getTurn();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Tl <em>Tl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tl</em>'.
   * @see org.xtext.demo.mydsl.demo.Tl
   * @generated
   */
  EClass getTl();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Tr <em>Tr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tr</em>'.
   * @see org.xtext.demo.mydsl.demo.Tr
   * @generated
   */
  EClass getTr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DemoFactory getDemoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ModelImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ImageImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__INSTRUCTION = eINSTANCE.getImage_Instruction();

    /**
     * The meta object literal for the '<em><b>Suite inst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__SUITE_INST = eINSTANCE.getImage_Suite_inst();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl <em>Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.SuiteImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getSuite()
     * @generated
     */
    EClass SUITE = eINSTANCE.getSuite();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUITE__INSTRUCTION = eINSTANCE.getSuite_Instruction();

    /**
     * The meta object literal for the '<em><b>Suite inst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUITE__SUITE_INST = eINSTANCE.getSuite_Suite_inst();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.InstImpl <em>Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.InstImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getInst()
     * @generated
     */
    EClass INST = eINSTANCE.getInst();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INST__NOMBRE = eINSTANCE.getInst_Nombre();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.GoImpl <em>Go</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.GoImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getGo()
     * @generated
     */
    EClass GO = eINSTANCE.getGo();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TurnImpl <em>Turn</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TurnImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTurn()
     * @generated
     */
    EClass TURN = eINSTANCE.getTurn();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TlImpl <em>Tl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TlImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTl()
     * @generated
     */
    EClass TL = eINSTANCE.getTl();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TrImpl <em>Tr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TrImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTr()
     * @generated
     */
    EClass TR = eINSTANCE.getTr();

  }

} //DemoPackage
