/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.demo.mydsl.demo.DemoFactory
 * @model kind="package"
 * @generated
 */
public interface DemoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "demo";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/demo/mydsl/Demo";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "demo";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DemoPackage eINSTANCE = org.xtext.demo.mydsl.demo.impl.DemoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ModelImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.AbstractElementImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ImageImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 2;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__INSTRUCTION = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Suite inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__SUITE_INST = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl <em>Suite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.SuiteImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getSuite()
   * @generated
   */
  int SUITE = 3;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE__INSTRUCTION = 0;

  /**
   * The feature id for the '<em><b>Suite inst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE__SUITE_INST = 1;

  /**
   * The number of structural features of the '<em>Suite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUITE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.InstImpl <em>Inst</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.InstImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getInst()
   * @generated
   */
  int INST = 4;

  /**
   * The number of structural features of the '<em>Inst</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INST_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.GoImpl <em>Go</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.GoImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getGo()
   * @generated
   */
  int GO = 5;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__NOMBRE = INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_FEATURE_COUNT = INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TurnImpl <em>Turn</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TurnImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTurn()
   * @generated
   */
  int TURN = 6;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN__NOMBRE = INST_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Turn</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_FEATURE_COUNT = INST_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TlImpl <em>Tl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TlImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTl()
   * @generated
   */
  int TL = 7;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TL__NOMBRE = TURN__NOMBRE;

  /**
   * The number of structural features of the '<em>Tl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TL_FEATURE_COUNT = TURN_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.TrImpl <em>Tr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.TrImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTr()
   * @generated
   */
  int TR = 8;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TR__NOMBRE = TURN__NOMBRE;

  /**
   * The number of structural features of the '<em>Tr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TR_FEATURE_COUNT = TURN_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ProcedureImpl <em>Procedure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ProcedureImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getProcedure()
   * @generated
   */
  int PROCEDURE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__PARAMETERS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Image</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__IMAGE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Procedure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.formal_parameter_listImpl <em>formal parameter list</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.formal_parameter_listImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getformal_parameter_list()
   * @generated
   */
  int FORMAL_PARAMETER_LIST = 10;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_PARAMETER_LIST__PARAMETER = 0;

  /**
   * The number of structural features of the '<em>formal parameter list</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_PARAMETER_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.ProcedureCallImpl <em>Procedure Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.ProcedureCallImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getProcedureCall()
   * @generated
   */
  int PROCEDURE_CALL = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_CALL__NAME = INST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_CALL__ARGUMENTS = INST_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Procedure Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_CALL_FEATURE_COUNT = INST_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.demo.mydsl.demo.impl.argument_listImpl <em>argument list</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.demo.mydsl.demo.impl.argument_listImpl
   * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getargument_list()
   * @generated
   */
  int ARGUMENT_LIST = 12;

  /**
   * The feature id for the '<em><b>Argument</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_LIST__ARGUMENT = 0;

  /**
   * The number of structural features of the '<em>argument list</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_LIST_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.demo.mydsl.demo.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.demo.mydsl.demo.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.demo.mydsl.demo.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.demo.mydsl.demo.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see org.xtext.demo.mydsl.demo.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Image#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.xtext.demo.mydsl.demo.Image#getInstruction()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Instruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Image#getSuite_inst <em>Suite inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Suite inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Image#getSuite_inst()
   * @see #getImage()
   * @generated
   */
  EReference getImage_Suite_inst();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Suite <em>Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Suite</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite
   * @generated
   */
  EClass getSuite();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Suite#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite#getInstruction()
   * @see #getSuite()
   * @generated
   */
  EReference getSuite_Instruction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Suite#getSuite_inst <em>Suite inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Suite inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Suite#getSuite_inst()
   * @see #getSuite()
   * @generated
   */
  EReference getSuite_Suite_inst();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Inst <em>Inst</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inst</em>'.
   * @see org.xtext.demo.mydsl.demo.Inst
   * @generated
   */
  EClass getInst();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Go <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go</em>'.
   * @see org.xtext.demo.mydsl.demo.Go
   * @generated
   */
  EClass getGo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.demo.mydsl.demo.Go#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.demo.mydsl.demo.Go#getNombre()
   * @see #getGo()
   * @generated
   */
  EAttribute getGo_Nombre();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Turn <em>Turn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn</em>'.
   * @see org.xtext.demo.mydsl.demo.Turn
   * @generated
   */
  EClass getTurn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.demo.mydsl.demo.Turn#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.demo.mydsl.demo.Turn#getNombre()
   * @see #getTurn()
   * @generated
   */
  EAttribute getTurn_Nombre();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Tl <em>Tl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tl</em>'.
   * @see org.xtext.demo.mydsl.demo.Tl
   * @generated
   */
  EClass getTl();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Tr <em>Tr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tr</em>'.
   * @see org.xtext.demo.mydsl.demo.Tr
   * @generated
   */
  EClass getTr();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.Procedure <em>Procedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Procedure</em>'.
   * @see org.xtext.demo.mydsl.demo.Procedure
   * @generated
   */
  EClass getProcedure();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.demo.mydsl.demo.Procedure#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.demo.mydsl.demo.Procedure#getName()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Procedure#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see org.xtext.demo.mydsl.demo.Procedure#getParameters()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.Procedure#getImage <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Image</em>'.
   * @see org.xtext.demo.mydsl.demo.Procedure#getImage()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Image();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.formal_parameter_list <em>formal parameter list</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>formal parameter list</em>'.
   * @see org.xtext.demo.mydsl.demo.formal_parameter_list
   * @generated
   */
  EClass getformal_parameter_list();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.demo.mydsl.demo.formal_parameter_list#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameter</em>'.
   * @see org.xtext.demo.mydsl.demo.formal_parameter_list#getParameter()
   * @see #getformal_parameter_list()
   * @generated
   */
  EAttribute getformal_parameter_list_Parameter();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.ProcedureCall <em>Procedure Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Procedure Call</em>'.
   * @see org.xtext.demo.mydsl.demo.ProcedureCall
   * @generated
   */
  EClass getProcedureCall();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.demo.mydsl.demo.ProcedureCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.demo.mydsl.demo.ProcedureCall#getName()
   * @see #getProcedureCall()
   * @generated
   */
  EAttribute getProcedureCall_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.demo.mydsl.demo.ProcedureCall#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arguments</em>'.
   * @see org.xtext.demo.mydsl.demo.ProcedureCall#getArguments()
   * @see #getProcedureCall()
   * @generated
   */
  EReference getProcedureCall_Arguments();

  /**
   * Returns the meta object for class '{@link org.xtext.demo.mydsl.demo.argument_list <em>argument list</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>argument list</em>'.
   * @see org.xtext.demo.mydsl.demo.argument_list
   * @generated
   */
  EClass getargument_list();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.demo.mydsl.demo.argument_list#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Argument</em>'.
   * @see org.xtext.demo.mydsl.demo.argument_list#getArgument()
   * @see #getargument_list()
   * @generated
   */
  EAttribute getargument_list_Argument();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DemoFactory getDemoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ModelImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.AbstractElementImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ImageImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__INSTRUCTION = eINSTANCE.getImage_Instruction();

    /**
     * The meta object literal for the '<em><b>Suite inst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMAGE__SUITE_INST = eINSTANCE.getImage_Suite_inst();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl <em>Suite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.SuiteImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getSuite()
     * @generated
     */
    EClass SUITE = eINSTANCE.getSuite();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUITE__INSTRUCTION = eINSTANCE.getSuite_Instruction();

    /**
     * The meta object literal for the '<em><b>Suite inst</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUITE__SUITE_INST = eINSTANCE.getSuite_Suite_inst();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.InstImpl <em>Inst</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.InstImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getInst()
     * @generated
     */
    EClass INST = eINSTANCE.getInst();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.GoImpl <em>Go</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.GoImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getGo()
     * @generated
     */
    EClass GO = eINSTANCE.getGo();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO__NOMBRE = eINSTANCE.getGo_Nombre();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TurnImpl <em>Turn</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TurnImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTurn()
     * @generated
     */
    EClass TURN = eINSTANCE.getTurn();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN__NOMBRE = eINSTANCE.getTurn_Nombre();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TlImpl <em>Tl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TlImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTl()
     * @generated
     */
    EClass TL = eINSTANCE.getTl();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.TrImpl <em>Tr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.TrImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getTr()
     * @generated
     */
    EClass TR = eINSTANCE.getTr();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ProcedureImpl <em>Procedure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ProcedureImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getProcedure()
     * @generated
     */
    EClass PROCEDURE = eINSTANCE.getProcedure();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__NAME = eINSTANCE.getProcedure_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__PARAMETERS = eINSTANCE.getProcedure_Parameters();

    /**
     * The meta object literal for the '<em><b>Image</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__IMAGE = eINSTANCE.getProcedure_Image();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.formal_parameter_listImpl <em>formal parameter list</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.formal_parameter_listImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getformal_parameter_list()
     * @generated
     */
    EClass FORMAL_PARAMETER_LIST = eINSTANCE.getformal_parameter_list();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMAL_PARAMETER_LIST__PARAMETER = eINSTANCE.getformal_parameter_list_Parameter();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.ProcedureCallImpl <em>Procedure Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.ProcedureCallImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getProcedureCall()
     * @generated
     */
    EClass PROCEDURE_CALL = eINSTANCE.getProcedureCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE_CALL__NAME = eINSTANCE.getProcedureCall_Name();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE_CALL__ARGUMENTS = eINSTANCE.getProcedureCall_Arguments();

    /**
     * The meta object literal for the '{@link org.xtext.demo.mydsl.demo.impl.argument_listImpl <em>argument list</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.demo.mydsl.demo.impl.argument_listImpl
     * @see org.xtext.demo.mydsl.demo.impl.DemoPackageImpl#getargument_list()
     * @generated
     */
    EClass ARGUMENT_LIST = eINSTANCE.getargument_list();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENT_LIST__ARGUMENT = eINSTANCE.getargument_list_Argument();

  }

} //DemoPackage
