/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Procedure Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.demo.mydsl.demo.ProcedureCall#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.demo.mydsl.demo.ProcedureCall#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.demo.mydsl.demo.DemoPackage#getProcedureCall()
 * @model
 * @generated
 */
public interface ProcedureCall extends Inst
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.demo.mydsl.demo.DemoPackage#getProcedureCall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.demo.mydsl.demo.ProcedureCall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference.
   * @see #setArguments(argument_list)
   * @see org.xtext.demo.mydsl.demo.DemoPackage#getProcedureCall_Arguments()
   * @model containment="true"
   * @generated
   */
  argument_list getArguments();

  /**
   * Sets the value of the '{@link org.xtext.demo.mydsl.demo.ProcedureCall#getArguments <em>Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arguments</em>' containment reference.
   * @see #getArguments()
   * @generated
   */
  void setArguments(argument_list value);

} // ProcedureCall
