/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.demo.mydsl.demo.DemoPackage#getTl()
 * @model
 * @generated
 */
public interface Tl extends Turn
{
} // Tl
