/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.demo.mydsl.demo.DemoPackage#getTurn()
 * @model
 * @generated
 */
public interface Turn extends Inst
{
} // Turn
