/*
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DemoGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsAbstractElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//    elements+=AbstractElement* ;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=AbstractElement*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_0() { return cElementsAbstractElementParserRuleCall_0; }
	}
	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cImageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cProcedureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractElement:
		//    Image | Procedure
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Image | Procedure
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Image
		public RuleCall getImageParserRuleCall_0() { return cImageParserRuleCall_0; }
		
		//Procedure
		public RuleCall getProcedureParserRuleCall_1() { return cProcedureParserRuleCall_1; }
	}
	public class ImageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Image");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInstructionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cInstructionInstParserRuleCall_0_0 = (RuleCall)cInstructionAssignment_0.eContents().get(0);
		private final Assignment cSuite_instAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSuite_instSuiteParserRuleCall_1_0 = (RuleCall)cSuite_instAssignment_1.eContents().get(0);
		
		//Image:
		//    instruction=Inst suite_inst=Suite;
		@Override public ParserRule getRule() { return rule; }
		
		//instruction=Inst suite_inst=Suite
		public Group getGroup() { return cGroup; }
		
		//instruction=Inst
		public Assignment getInstructionAssignment_0() { return cInstructionAssignment_0; }
		
		//Inst
		public RuleCall getInstructionInstParserRuleCall_0_0() { return cInstructionInstParserRuleCall_0_0; }
		
		//suite_inst=Suite
		public Assignment getSuite_instAssignment_1() { return cSuite_instAssignment_1; }
		
		//Suite
		public RuleCall getSuite_instSuiteParserRuleCall_1_0() { return cSuite_instSuiteParserRuleCall_1_0; }
	}
	public class SuiteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Suite");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cInstructionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cInstructionInstParserRuleCall_0_0_0 = (RuleCall)cInstructionAssignment_0_0.eContents().get(0);
		private final Assignment cSuite_instAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cSuite_instSuiteParserRuleCall_0_1_0 = (RuleCall)cSuite_instAssignment_0_1.eContents().get(0);
		private final Action cSuiteAction_1 = (Action)cAlternatives.eContents().get(1);
		
		//Suite:
		//    instruction=Inst suite_inst=Suite | {Suite};
		@Override public ParserRule getRule() { return rule; }
		
		//instruction=Inst suite_inst=Suite | {Suite}
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//instruction=Inst suite_inst=Suite
		public Group getGroup_0() { return cGroup_0; }
		
		//instruction=Inst
		public Assignment getInstructionAssignment_0_0() { return cInstructionAssignment_0_0; }
		
		//Inst
		public RuleCall getInstructionInstParserRuleCall_0_0_0() { return cInstructionInstParserRuleCall_0_0_0; }
		
		//suite_inst=Suite
		public Assignment getSuite_instAssignment_0_1() { return cSuite_instAssignment_0_1; }
		
		//Suite
		public RuleCall getSuite_instSuiteParserRuleCall_0_1_0() { return cSuite_instSuiteParserRuleCall_0_1_0; }
		
		//{Suite}
		public Action getSuiteAction_1() { return cSuiteAction_1; }
	}
	public class InstElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Inst");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTurnParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cProcedureCallParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Inst:
		//    Go | Turn | ProcedureCall;
		@Override public ParserRule getRule() { return rule; }
		
		//Go | Turn | ProcedureCall
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Go
		public RuleCall getGoParserRuleCall_0() { return cGoParserRuleCall_0; }
		
		//Turn
		public RuleCall getTurnParserRuleCall_1() { return cTurnParserRuleCall_1; }
		
		//ProcedureCall
		public RuleCall getProcedureCallParserRuleCall_2() { return cProcedureCallParserRuleCall_2; }
	}
	public class GoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Go");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAvancerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreINTTerminalRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		
		//Go:
		//    'avancer' nombre=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'avancer' nombre=INT
		public Group getGroup() { return cGroup; }
		
		//'avancer'
		public Keyword getAvancerKeyword_0() { return cAvancerKeyword_0; }
		
		//nombre=INT
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//INT
		public RuleCall getNombreINTTerminalRuleCall_1_0() { return cNombreINTTerminalRuleCall_1_0; }
	}
	public class TurnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Turn");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTlParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTrParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Turn:
		//    Tl | Tr;
		@Override public ParserRule getRule() { return rule; }
		
		//Tl | Tr
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Tl
		public RuleCall getTlParserRuleCall_0() { return cTlParserRuleCall_0; }
		
		//Tr
		public RuleCall getTrParserRuleCall_1() { return cTrParserRuleCall_1; }
	}
	public class TlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Tl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGaucheKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreINTTerminalRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		
		//Tl:
		//    'gauche' nombre=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'gauche' nombre=INT
		public Group getGroup() { return cGroup; }
		
		//'gauche'
		public Keyword getGaucheKeyword_0() { return cGaucheKeyword_0; }
		
		//nombre=INT
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//INT
		public RuleCall getNombreINTTerminalRuleCall_1_0() { return cNombreINTTerminalRuleCall_1_0; }
	}
	public class TrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Tr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDroitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreINTTerminalRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		
		//Tr:
		//    'droit' nombre=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'droit' nombre=INT
		public Group getGroup() { return cGroup; }
		
		//'droit'
		public Keyword getDroitKeyword_0() { return cDroitKeyword_0; }
		
		//nombre=INT
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//INT
		public RuleCall getNombreINTTerminalRuleCall_1_0() { return cNombreINTTerminalRuleCall_1_0; }
	}
	public class ProcedureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.Procedure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcedureKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cParametersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParametersFormal_parameter_listParserRuleCall_2_0 = (RuleCall)cParametersAssignment_2.eContents().get(0);
		private final Assignment cImageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImageImageParserRuleCall_3_0 = (RuleCall)cImageAssignment_3.eContents().get(0);
		private final Keyword cFinProcedureKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Procedure:
		//    'procedure' name=ID ( parameters=formal_parameter_list ) ?
		//        image=Image
		//    'finProcedure';
		@Override public ParserRule getRule() { return rule; }
		
		//'procedure' name=ID ( parameters=formal_parameter_list ) ?
		//    image=Image
		//'finProcedure'
		public Group getGroup() { return cGroup; }
		
		//'procedure'
		public Keyword getProcedureKeyword_0() { return cProcedureKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//( parameters=formal_parameter_list ) ?
		public Assignment getParametersAssignment_2() { return cParametersAssignment_2; }
		
		//formal_parameter_list
		public RuleCall getParametersFormal_parameter_listParserRuleCall_2_0() { return cParametersFormal_parameter_listParserRuleCall_2_0; }
		
		//image=Image
		public Assignment getImageAssignment_3() { return cImageAssignment_3; }
		
		//Image
		public RuleCall getImageImageParserRuleCall_3_0() { return cImageImageParserRuleCall_3_0; }
		
		//'finProcedure'
		public Keyword getFinProcedureKeyword_4() { return cFinProcedureKeyword_4; }
	}
	public class Formal_parameter_listElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.formal_parameter_list");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cParameterAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cParameterIDTerminalRuleCall_1_0 = (RuleCall)cParameterAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParameterAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParameterIDTerminalRuleCall_2_1_0 = (RuleCall)cParameterAssignment_2_1.eContents().get(0);
		
		//formal_parameter_list:
		//    ':' parameter+=ID ( ":" parameter+=ID ) *
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//':' parameter+=ID ( ":" parameter+=ID ) *
		public Group getGroup() { return cGroup; }
		
		//':'
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }
		
		//parameter+=ID
		public Assignment getParameterAssignment_1() { return cParameterAssignment_1; }
		
		//ID
		public RuleCall getParameterIDTerminalRuleCall_1_0() { return cParameterIDTerminalRuleCall_1_0; }
		
		//( ":" parameter+=ID ) *
		public Group getGroup_2() { return cGroup_2; }
		
		//":"
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }
		
		//parameter+=ID
		public Assignment getParameterAssignment_2_1() { return cParameterAssignment_2_1; }
		
		//ID
		public RuleCall getParameterIDTerminalRuleCall_2_1_0() { return cParameterIDTerminalRuleCall_2_1_0; }
	}
	public class ProcedureCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.ProcedureCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cArgumentsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cArgumentsArgument_listParserRuleCall_1_0 = (RuleCall)cArgumentsAssignment_1.eContents().get(0);
		
		//ProcedureCall:
		//    name=ID arguments=argument_list ? ;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID arguments=argument_list ?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//arguments=argument_list ?
		public Assignment getArgumentsAssignment_1() { return cArgumentsAssignment_1; }
		
		//argument_list
		public RuleCall getArgumentsArgument_listParserRuleCall_1_0() { return cArgumentsArgument_listParserRuleCall_1_0; }
	}
	public class Argument_listElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.demo.mydsl.Demo.argument_list");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cArgumentAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cArgumentINTTerminalRuleCall_0_0 = (RuleCall)cArgumentAssignment_0.eContents().get(0);
		private final Assignment cArgumentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cArgumentINTTerminalRuleCall_1_0 = (RuleCall)cArgumentAssignment_1.eContents().get(0);
		
		//argument_list:
		//    argument+=INT ( argument+=INT ) * ;
		@Override public ParserRule getRule() { return rule; }
		
		//argument+=INT ( argument+=INT ) *
		public Group getGroup() { return cGroup; }
		
		//argument+=INT
		public Assignment getArgumentAssignment_0() { return cArgumentAssignment_0; }
		
		//INT
		public RuleCall getArgumentINTTerminalRuleCall_0_0() { return cArgumentINTTerminalRuleCall_0_0; }
		
		//( argument+=INT ) *
		public Assignment getArgumentAssignment_1() { return cArgumentAssignment_1; }
		
		//INT
		public RuleCall getArgumentINTTerminalRuleCall_1_0() { return cArgumentINTTerminalRuleCall_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final AbstractElementElements pAbstractElement;
	private final ImageElements pImage;
	private final SuiteElements pSuite;
	private final InstElements pInst;
	private final GoElements pGo;
	private final TurnElements pTurn;
	private final TlElements pTl;
	private final TrElements pTr;
	private final ProcedureElements pProcedure;
	private final Formal_parameter_listElements pFormal_parameter_list;
	private final ProcedureCallElements pProcedureCall;
	private final Argument_listElements pArgument_list;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DemoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pImage = new ImageElements();
		this.pSuite = new SuiteElements();
		this.pInst = new InstElements();
		this.pGo = new GoElements();
		this.pTurn = new TurnElements();
		this.pTl = new TlElements();
		this.pTr = new TrElements();
		this.pProcedure = new ProcedureElements();
		this.pFormal_parameter_list = new Formal_parameter_listElements();
		this.pProcedureCall = new ProcedureCallElements();
		this.pArgument_list = new Argument_listElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.demo.mydsl.Demo".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    elements+=AbstractElement* ;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//AbstractElement:
	//    Image | Procedure
	//;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}
	
	//Image:
	//    instruction=Inst suite_inst=Suite;
	public ImageElements getImageAccess() {
		return pImage;
	}
	
	public ParserRule getImageRule() {
		return getImageAccess().getRule();
	}
	
	//Suite:
	//    instruction=Inst suite_inst=Suite | {Suite};
	public SuiteElements getSuiteAccess() {
		return pSuite;
	}
	
	public ParserRule getSuiteRule() {
		return getSuiteAccess().getRule();
	}
	
	//Inst:
	//    Go | Turn | ProcedureCall;
	public InstElements getInstAccess() {
		return pInst;
	}
	
	public ParserRule getInstRule() {
		return getInstAccess().getRule();
	}
	
	//Go:
	//    'avancer' nombre=INT;
	public GoElements getGoAccess() {
		return pGo;
	}
	
	public ParserRule getGoRule() {
		return getGoAccess().getRule();
	}
	
	//Turn:
	//    Tl | Tr;
	public TurnElements getTurnAccess() {
		return pTurn;
	}
	
	public ParserRule getTurnRule() {
		return getTurnAccess().getRule();
	}
	
	//Tl:
	//    'gauche' nombre=INT;
	public TlElements getTlAccess() {
		return pTl;
	}
	
	public ParserRule getTlRule() {
		return getTlAccess().getRule();
	}
	
	//Tr:
	//    'droit' nombre=INT;
	public TrElements getTrAccess() {
		return pTr;
	}
	
	public ParserRule getTrRule() {
		return getTrAccess().getRule();
	}
	
	//Procedure:
	//    'procedure' name=ID ( parameters=formal_parameter_list ) ?
	//        image=Image
	//    'finProcedure';
	public ProcedureElements getProcedureAccess() {
		return pProcedure;
	}
	
	public ParserRule getProcedureRule() {
		return getProcedureAccess().getRule();
	}
	
	//formal_parameter_list:
	//    ':' parameter+=ID ( ":" parameter+=ID ) *
	//;
	public Formal_parameter_listElements getFormal_parameter_listAccess() {
		return pFormal_parameter_list;
	}
	
	public ParserRule getFormal_parameter_listRule() {
		return getFormal_parameter_listAccess().getRule();
	}
	
	//ProcedureCall:
	//    name=ID arguments=argument_list ? ;
	public ProcedureCallElements getProcedureCallAccess() {
		return pProcedureCall;
	}
	
	public ParserRule getProcedureCallRule() {
		return getProcedureCallAccess().getRule();
	}
	
	//argument_list:
	//    argument+=INT ( argument+=INT ) * ;
	public Argument_listElements getArgument_listAccess() {
		return pArgument_list;
	}
	
	public ParserRule getArgument_listRule() {
		return getArgument_listAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
