/*
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.demo.mydsl.parser.antlr.internal.InternalDemoParser;
import org.xtext.demo.mydsl.services.DemoGrammarAccess;

public class DemoParser extends AbstractAntlrParser {

	@Inject
	private DemoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDemoParser createParser(XtextTokenStream stream) {
		return new InternalDemoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DemoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DemoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
