/*
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDemoScopeProvider extends DelegatingScopeProvider {
}
