/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.demo.mydsl.demo.DemoPackage;
import org.xtext.demo.mydsl.demo.Inst;
import org.xtext.demo.mydsl.demo.Suite;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Suite</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl#getInstruction <em>Instruction</em>}</li>
 *   <li>{@link org.xtext.demo.mydsl.demo.impl.SuiteImpl#getSuite_inst <em>Suite inst</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SuiteImpl extends MinimalEObjectImpl.Container implements Suite
{
  /**
   * The cached value of the '{@link #getInstruction() <em>Instruction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstruction()
   * @generated
   * @ordered
   */
  protected Inst instruction;

  /**
   * The cached value of the '{@link #getSuite_inst() <em>Suite inst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuite_inst()
   * @generated
   * @ordered
   */
  protected Suite suite_inst;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuiteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DemoPackage.Literals.SUITE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Inst getInstruction()
  {
    return instruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInstruction(Inst newInstruction, NotificationChain msgs)
  {
    Inst oldInstruction = instruction;
    instruction = newInstruction;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DemoPackage.SUITE__INSTRUCTION, oldInstruction, newInstruction);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstruction(Inst newInstruction)
  {
    if (newInstruction != instruction)
    {
      NotificationChain msgs = null;
      if (instruction != null)
        msgs = ((InternalEObject)instruction).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DemoPackage.SUITE__INSTRUCTION, null, msgs);
      if (newInstruction != null)
        msgs = ((InternalEObject)newInstruction).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DemoPackage.SUITE__INSTRUCTION, null, msgs);
      msgs = basicSetInstruction(newInstruction, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DemoPackage.SUITE__INSTRUCTION, newInstruction, newInstruction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Suite getSuite_inst()
  {
    return suite_inst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSuite_inst(Suite newSuite_inst, NotificationChain msgs)
  {
    Suite oldSuite_inst = suite_inst;
    suite_inst = newSuite_inst;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DemoPackage.SUITE__SUITE_INST, oldSuite_inst, newSuite_inst);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuite_inst(Suite newSuite_inst)
  {
    if (newSuite_inst != suite_inst)
    {
      NotificationChain msgs = null;
      if (suite_inst != null)
        msgs = ((InternalEObject)suite_inst).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DemoPackage.SUITE__SUITE_INST, null, msgs);
      if (newSuite_inst != null)
        msgs = ((InternalEObject)newSuite_inst).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DemoPackage.SUITE__SUITE_INST, null, msgs);
      msgs = basicSetSuite_inst(newSuite_inst, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DemoPackage.SUITE__SUITE_INST, newSuite_inst, newSuite_inst));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DemoPackage.SUITE__INSTRUCTION:
        return basicSetInstruction(null, msgs);
      case DemoPackage.SUITE__SUITE_INST:
        return basicSetSuite_inst(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DemoPackage.SUITE__INSTRUCTION:
        return getInstruction();
      case DemoPackage.SUITE__SUITE_INST:
        return getSuite_inst();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DemoPackage.SUITE__INSTRUCTION:
        setInstruction((Inst)newValue);
        return;
      case DemoPackage.SUITE__SUITE_INST:
        setSuite_inst((Suite)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DemoPackage.SUITE__INSTRUCTION:
        setInstruction((Inst)null);
        return;
      case DemoPackage.SUITE__SUITE_INST:
        setSuite_inst((Suite)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DemoPackage.SUITE__INSTRUCTION:
        return instruction != null;
      case DemoPackage.SUITE__SUITE_INST:
        return suite_inst != null;
    }
    return super.eIsSet(featureID);
  }

} //SuiteImpl
