/**
 * generated by Xtext 2.26.0
 */
package org.xtext.demo.mydsl.demo.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.demo.mydsl.demo.DemoPackage;
import org.xtext.demo.mydsl.demo.Tr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrImpl extends TurnImpl implements Tr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DemoPackage.Literals.TR;
  }

} //TrImpl
